### ISSUE TITLE
Use cases feedback - consent codes and data use restrictions

### ISSUE THREAD

**Issue by mcourtot** [Ensembl/schemas#1]
MTT discussed the need for consent codes and data use restrictions representation in the API. We developed [DUO](https://github.com/EBISPOT/DUO) to help with this. 

cc @mbaudis

**Comment by kozbo** [comment]
+1

**Comment by lairdm** [comment]
Added, but I did mull if this rates as a full use case or should be an optional attribute of the returned results (ie. part of the data format specifications)

**Comment by mcourtot** [comment]
Tbh, we're not sure at this stage. We know we'll need to return consent codes/data use permissions, but not sure where those will live yet. Note that Francis Jeanson, is just starting to work on this as part of the Beacon project in collaboration with ADA-M (we talked to ADA-M devs and Francis to coordinate efforts and use DUO for machine readability). I'll point him to this thread.

**Comment by FrancisJMR** [comment]
Hi all, 
I'm currently looking into adapting the ADA-M specifications to an avro schema, as used by the Beacon project. This should help anyone adopt the specifications irrespective of their platform. I'll be following-up with Miro from DNA Stack to compare with the Beacon format.

Indeed, returning a field with one or mode consent codes as defined in (http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005772) is possible but ADA-M allows for very fine grained specifications for categories and requirements -- I think consent codes could be subsumed under an ADA-M spec.  I'm still studying this to make a proposal on the direction to take.

Happy to discuss further!
