### ISSUE TITLE
Use case: Fetch all variants for males between 40 and 50 years old

### ISSUE THREAD

**Issue by kozbo** [Ensembl/schemas#10]
This can be done via calls from the client today. Does this use case require that the filtering be done on the server?

**Comment by lairdm** [comment]
I'm not sure if this can be done in the current reference server. Based on the stakeholder interviews, this kind of server side filtering is desired for the next iteration of the API, which is what we're aiming for with these use cases.

**Comment by kozbo** [comment]
@lairdm ok, thanks, makes sense.
